services:
  db:
    image: postgres:17
    container_name: authdb
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - .:/usr/src/app
    command: >
      streamlit run main.py --server.address=0.0.0.0
    restart: unless-stopped

volumes:
  db_data: