services:
  db:
    image: postgres:17
    container_name: authdb
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  cq_db:
    image: postgres:17
    container_name: cq_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - cq_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  transcription_db:
    image: postgres:17
    container_name: transcription_db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - transcription_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dig4el_logic_ui
    env_file:
      - .env
    depends_on:
      - db
      - cq_db
      - transcription_db
    expose:
      - "8501"  # internal Docker network port
    command: >
      streamlit run main.py --server.address=0.0.0.0
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  db_data:
  cq_db_data:
  transcription_db_data:
  certbot_certs:
